### PR TITLE
PostgreSQL migration

### PR DESCRIPTION
**Pull request by SirNoob97**
Issues related:

* #2 
* #29 

Pending:
* SQL script for init the DB to discard dummy-data and avoid hibernate interventions.
* Test for services and controllers.

### CODE REVIEW

**Comment by SirNoob97** [comment]
Read this to understand why I change the ClientController paths [Rest url conventions](https://www.thecodebuzz.com/restful-api-url-naming-conventions-best-practices/).

**Comment by kgotlelelo-cmd** [comment]
Thanks.. I checked the blog
There where conflicts hopefully I resolved them correctly

**Comment by kgotlelelo-cmd** [comment]
I think You made a mistake of dockercompose file, then env_file should be .env.dev not postgres

**Comment by SirNoob97** [comment]
the .env.dev file to inject env variables in the docker-compose file the postgres.env file is for the backend container

**Pull request merged**
